"""Database Hardening Fixed

Revision ID: d81f80d37bff
Revises: 9b2d8c7f1a3e
Create Date: 2026-09-15 20:11:07.659919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd81f80d37bff'
down_revision: Union[str, None] = '9b2d8c7f1a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_events',
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('what_was_abnormal', sa.String(length=255), nullable=False),
    sa.Column('baseline_reference', sa.String(length=255), nullable=False),
    sa.Column('observed_value', sa.String(length=255), nullable=False),
    sa.Column('anomaly_signal', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_events_mine_id'), 'anomaly_events', ['mine_id'], unique=False)
    op.create_table('recurring_issues',
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('recurrence_count', sa.Integer(), nullable=False),
    sa.Column('time_window_days', sa.Integer(), nullable=False),
    sa.Column('location_details', sa.String(length=255), nullable=True),
    sa.Column('issue_category', sa.String(length=100), nullable=True),
    sa.Column('related_record_ids', sa.JSON(), nullable=False),
    sa.Column('recurrence_signal', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_issues_mine_id'), 'recurring_issues', ['mine_id'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_recurring_issues_mine_id'), table_name='recurring_issues')
    op.drop_table('recurring_issues')
    op.drop_index(op.f('ix_anomaly_events_mine_id'), table_name='anomaly_events')
    op.drop_table('anomaly_events')
    # ### end Alembic commands ###

