import uuid
from datetime import datetime
from typing import Optional, Dict, Any
from pydantic import BaseModel, ConfigDict
from app.models.field import InspectionStatus, SafetyEventType, SafetyEventSeverity, ActionStatus, SafetyEventCategory

class SafetyEventCreate(BaseModel):
    mine_id: uuid.UUID
    type: Optional[SafetyEventType] = None
    category: Optional[SafetyEventCategory] = None
    severity: Optional[SafetyEventSeverity] = None
    description: str
    location_details: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    is_anonymous: bool = False
    idempotency_key: Optional[str] = None
    
    # Allow AI fields to be passed on creation if generated by Copilot
    ai_event_type: Optional[SafetyEventType] = None
    ai_category: Optional[SafetyEventCategory] = None
    ai_severity: Optional[SafetyEventSeverity] = None

class SafetyEventResponse(BaseModel):
    id: uuid.UUID
    mine_id: uuid.UUID
    type: Optional[SafetyEventType]
    category: Optional[SafetyEventCategory]
    severity: Optional[SafetyEventSeverity]
    description: str
    
    # AI Tracking
    ai_event_type: Optional[SafetyEventType]
    ai_category: Optional[SafetyEventCategory]
    ai_severity: Optional[SafetyEventSeverity]
    ai_prediction_timestamp: Optional[datetime]
    
    # Review Tracking
    human_reviewed_at: Optional[datetime]
    human_reviewer_id: Optional[uuid.UUID]
    is_ai_overridden: bool
    
    # Risk Engine Outputs
    risk_score: Optional[float]
    risk_level: Optional[str]
    risk_factors: Optional[Dict[str, Any]]
    is_recurring: bool
    
    location_details: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    date: datetime
    is_anonymous: bool
    reporter_id: Optional[uuid.UUID] = None
    idempotency_key: Optional[str] = None
    
    model_config = ConfigDict(from_attributes=True)

class CorrectiveActionResponse(BaseModel):
    id: uuid.UUID
    mine_id: uuid.UUID
    description: str
    assigned_to_user_id: Optional[uuid.UUID] = None
    due_date: datetime
    status: ActionStatus
    
    model_config = ConfigDict(from_attributes=True)
